@TanksAPI_HostAddress = http://localhost:5024

GET {{TanksAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TanksAPI_HostAddress}}/api/auth/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlmYWU3ZC0yNThmLTdiMWMtYmU4MS04ODdmNmI1NjcxOTEiLCJ1bmlxdWVfbmFtZSI6IlNla2lybyIsImp0aSI6ImUwYThiOTY1LTUzMTYtNGVkNS04MzlkLWJlNTk0MTRmZTM2MyIsImV4cCI6MTc4NTQwNDk5NiwiaXNzIjoiVGFua3NBUEkiLCJhdWQiOiJUYW5rc1VuaXR5In0.iYRlYHYst9qW2ZuxU5iJQZxpI-1EKFR2LIF1IBRuWQs
###

GET {{TanksAPI_HostAddress}}/api/auth/users/1
Accept: application/json

###

POST {{TanksAPI_HostAddress}}/api/auth/user
Content-Type: application/json

{
    "Username": "Manus",
    "PasswordHash": "Abyss"
}

###

DELETE {{TanksAPI_HostAddress}}/api/Auth/user/019fad26-ffe6-7729-a91c-7c5294c11c74

###

POST {{TanksAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Username": "Sekiro",
  "Password": "Mono"
}

###

POST {{TanksAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Username": "Sekiro",
  "Password": "Mono"
}