@TanksAPI_HostAddress = http://localhost:5024

GET {{TanksAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TanksAPI_HostAddress}}/api/auth/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlmYjJiZS1iODE4LTc4MjEtYTc3Ni0zMGYyNWU4ZTA2ODYiLCJ1bmlxdWVfbmFtZSI6IlNla2lybyIsImp0aSI6IjcxMDFiNjRkLWYyY2ItNGM5YS1iMDBjLWFhNmJhMzJkYjA2MyIsImV4cCI6MTc4NTQxMzk5NCwiaXNzIjoiVGFua3NBUEkiLCJhdWQiOiJUYW5rc1VuaXR5In0.5CsVAN6VnOVKi8zs2kp6Wj67K_cQo5a9VDe31an-h30
###

GET {{TanksAPI_HostAddress}}/api/auth/users/1
Accept: application/json

###

POST {{TanksAPI_HostAddress}}/api/auth/user
Content-Type: application/json

{
    "Username": "Manus",
    "PasswordHash": "Abyss"
}

###

DELETE {{TanksAPI_HostAddress}}/api/Auth/user/019fae7d-258f-7b1c-be81-887f6b567191

###

POST {{TanksAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "Username": "Sekiro",
  "Password": "Mono"
}

###

POST {{TanksAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Username": "Sekiro",
  "Password": "Mono"
}

###

GET {{TanksAPI_HostAddress}}/api/SaveGame
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlmYjJiZS1iODE4LTc4MjEtYTc3Ni0zMGYyNWU4ZTA2ODYiLCJ1bmlxdWVfbmFtZSI6IlNla2lybyIsImp0aSI6ImFjODg3ZWFmLTZjNTktNDgwOC04MTJmLTBmYThmNjZlYjkxNSIsImV4cCI6MTc4NTQxNTAwMSwiaXNzIjoiVGFua3NBUEkiLCJhdWQiOiJUYW5rc1VuaXR5In0.yR22ayz3bjyZ_NFGOSsKBtuTyGbfFBbnWbBzVV_IdwQ